# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TransformersTokenizer": "01_core.ipynb",
         "TextBlockWithCustomTokenizer": "01_core.ipynb",
         "from_df_with_custom_tok": "01_core.ipynb",
         "DropOutput": "01_core.ipynb",
         "create_transformer_classification_model": "01_core.ipynb",
         "transformers_classifier_learner": "01_core.ipynb",
         "Inferencer": "02_inference.ipynb",
         "main": "02_inference.ipynb"}

modules = ["core.py",
           "predict.py"]

doc_url = "https://kbressem.github.io/"

git_url = "https://github.com/kbressem/fastai-transformers/tree/master/"

def custom_doc_links(name): return None
